<a href="https://colab.research.google.com/github/YugalPNTL/Python/blob/master/3D_Transpose.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.arange(30).reshape(3, 2, 5)

print(a)
print(a.shape)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]]
(3, 2, 5)


In [3]:
b = np.transpose(a, (0, 2, 1))
print(b)
print(b.shape)

[[[ 0  5]
  [ 1  6]
  [ 2  7]
  [ 3  8]
  [ 4  9]]

 [[10 15]
  [11 16]
  [12 17]
  [13 18]
  [14 19]]

 [[20 25]
  [21 26]
  [22 27]
  [23 28]
  [24 29]]]
(3, 5, 2)


In [4]:
c = np.transpose(a, (2, 1, 0))
print(c)
print(c.shape)

[[[ 0 10 20]
  [ 5 15 25]]

 [[ 1 11 21]
  [ 6 16 26]]

 [[ 2 12 22]
  [ 7 17 27]]

 [[ 3 13 23]
  [ 8 18 28]]

 [[ 4 14 24]
  [ 9 19 29]]]
(5, 2, 3)
