In [1]:
import numpy as np

In [2]:
#converting python list to numpy 1-d array
a=[1,2,3]
print(a)

b=np.array(a)
print(b)


[1, 2, 3]
[1 2 3]


In [3]:
#converting python list of list to numpy 2d array
a=[[1,2],[3,4],[5,6],[7,8],[9,10]]
print(a)
b=np.array(a)
print(b)

[[1, 2], [3, 4], [5, 6], [7, 8], [9, 10]]
[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]


In [4]:
#arrange(start, stop, step size)--stop is exclusive
a=np.arange(0,40,3)
print(a)

[ 0  3  6  9 12 15 18 21 24 27 30 33 36 39]


In [5]:
a=np.zeros(5)
print(a)

b=np.zeros((3,5))
print(b)

c=np.ones(3)
print(c)

d=np.ones((3,4))
print(d)

#Pass Tuple for multi dimensions

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
[1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
a=np.linspace(0,20,5)
print(a)

#linspace(start Num of AP, End Num of AP, Total Num in AP)

[ 0.  5. 10. 15. 20.]


In [7]:
a=np.eye(5)
print(a)
#it generates identity matrix of specified numbers.

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


Random Numbers in Numpy


In [8]:
a=np.random.rand(5)
print(a)

b=np.random.rand(3,3)
print(b)

#rand generates random numbers between 0 t0 1 (1 excluded)


[0.98590066 0.58979473 0.7367604  0.85201751 0.29271775]
[[0.26938234 0.19932259 0.95579471]
 [0.27841437 0.77238592 0.03372595]
 [0.10808368 0.92733598 0.48859264]]


In [9]:
a=np.random.randn(5)
print(a)

b=np.random.randn(3,5)
print(b)

#randn takes sample from standard normal distribution

[-0.22326441  0.40312278  0.05306871 -1.09133458  0.7581706 ]
[[-0.24996793  0.32617499  0.01616952  0.53326725 -0.44713991]
 [-0.29318425 -2.35245669  1.64618652  0.03580189 -0.69477424]
 [-1.25354256  1.09224077  0.84524345  1.59003506 -1.2173204 ]]


In [10]:
a=np.random.randint(1,10,5)
print(a)

b=np.random.randint(5,60) #random int between 5 inclusive & 60 exclusive
print(b)

#randint random numbers between (start, stop, total numbers)
#start is inclusive but stop is exclusive

[3 9 6 8 4]
23


In [11]:
#reshape no of elements should be same as in array being shaped.
#reshape(rows,columns)--rows*columns=elements in array being reshaped
a=np.arange(0,30)
print(a)

b=a.reshape(5,6)
print(b)
print(b.shape)

print(b.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]
(5, 6)
int32


**Be careful to remember that shape is an attribute and not a function. Attributes do not have parenthesis following them**

In [12]:
a= np.random.randint(1,50,11)
print(a)

print(a.max())
print(a.argmax())
print(a.min())
print(a.argmin())

a.reshape(11,)


[ 6 44 38 39 32 41 42 43 30  5 24]
44
1
5
9


array([ 6, 44, 38, 39, 32, 41, 42, 43, 30,  5, 24])