In [1]:
import numpy as np

Transpose of any given Matrix is received when we interchange the rows and coloumns. If the given Matrix is $A$ then its transpose is shown as ![\begin{equation*} A =  \begin{pmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \\ 7 & 8 & 9 \end{pmatrix} \end{equation*}](https://render.githubusercontent.com/render/math?math=%5Cbegin%7Bequation*%7D%20A%20%3D%20%20%5Cbegin%7Bpmatrix%7D%201%20%26%202%20%26%203%20%5C%5C%204%20%26%205%20%26%206%20%5C%5C%207%20%26%208%20%26%209%20%5Cend%7Bpmatrix%7D%20%5Cend%7Bequation*%7D)
and ![\begin{equation*} B =  \begin{pmatrix} 10 & 11 & 12 \\ 13 & 14 & 15 \\ 16 & 17 & 18 \end{pmatrix} \end{equation*} ](https://render.githubusercontent.com/render/math?math=%5Cbegin%7Bequation*%7D%20B%20%3D%20%20%5Cbegin%7Bpmatrix%7D%2010%20%26%2011%20%26%2012%20%5C%5C%2013%20%26%2014%20%26%2015%20%5C%5C%2016%20%26%2017%20%26%2018%20%5Cend%7Bpmatrix%7D%20%5Cend%7Bequation*%7D%20)  to understand various properties of transpose

In [2]:
#Finding Transpose of Matrix A
a = np.array([[1, 2, 3], [4, 5, 6],[7,8,9]])
print(f'Original Matrix:\n{a}')

a_transpose = a.transpose()

print(f'Transposed Matriz:\n{a_transpose}')

Original Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposed Matriz:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


**Now we would understand various properties of Transpose**


1. $(AB)^{\rm T}$ = $B^{\rm T}$*$A^{\rm T}$

In [3]:
b = np.array([[10, 11, 12], [13, 14, 15],[16,17,18]])
c= np.matmul(a, b)
c_transpose = c.transpose()
print(f'Transposed Matriz of c is:\n{c_transpose}')
print(f'A Transpose Multiply B Traspose is :\n{np.matmul(b.transpose(), a.transpose())}')

Transposed Matriz of c is:
[[ 84 201 318]
 [ 90 216 342]
 [ 96 231 366]]
A Transpose Multiply B Traspose is :
[[ 84 201 318]
 [ 90 216 342]
 [ 96 231 366]]


2. $(A+B)^{\rm T}$ = $A^{\rm T}$+$B^{\rm T}$

In [4]:
d=np.transpose(np.add(a,b))
print(f'(A Plus B) Transpose is:\n{d}')
print(f'A Transpose Plus B Transpose is:\n{a.transpose()+b.transpose()}')


(A Plus B) Transpose is:
[[11 17 23]
 [13 19 25]
 [15 21 27]]
A Transpose Plus B Transpose is:
[[11 17 23]
 [13 19 25]
 [15 21 27]]


Symmetric Matrix: When Transpose of Matrix is Equal to Matrix

---


Skewed Symmetric Matrix: When Transpose of Matrix is not Equal to Matrix

3. For Any Square Matrix $A:$ $A+A^{\rm T}$ is symmetric Matrix and $A-A^{\rm T}$ is skewed symmetric matrix

In [5]:
print(f'(A Plus (A Transpose) is:\n{np.add(a,a.transpose())}')
print(f'(Transpose of A Plus (A Transpose) is:\n{np.add(a,a.transpose()).transpose()}')
print(f'(A Minus (A Transpose) is:\n{np.subtract(a,a.transpose())}')
print(f'(Transpose of A Minus (A Transpose) is:\n{np.subtract(a,a.transpose()).transpose()}')

(A Plus (A Transpose) is:
[[ 2  6 10]
 [ 6 10 14]
 [10 14 18]]
(Transpose of A Plus (A Transpose) is:
[[ 2  6 10]
 [ 6 10 14]
 [10 14 18]]
(A Minus (A Transpose) is:
[[ 0 -2 -4]
 [ 2  0 -2]
 [ 4  2  0]]
(Transpose of A Minus (A Transpose) is:
[[ 0  2  4]
 [-2  0  2]
 [-4 -2  0]]


4. when a Matrix is Multiplied by its Transpose the resultant Matrix is Symmetric Matrix. 
$A{\rm }$*$A^{\rm T}$ is always symmetric matrix

In [6]:
print(f'Matrix A is:\n{a}')
print(f'Transpose of Matrix A is:\n{a.transpose()}')
#Multiplying Matrix A with its Transpose
d=np.matmul(a,a.transpose())
print(f'Multiplication of Matrix A with its Transpose is:\n{d}')
print(f'Transpose of Matrix D is:\n{d.transpose()}')
print('Is Matrix D Symetric matrix?')
print(np.array_equal(d, d.transpose()))

Matrix A is:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose of Matrix A is:
[[1 4 7]
 [2 5 8]
 [3 6 9]]
Multiplication of Matrix A with its Transpose is:
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]
Transpose of Matrix D is:
[[ 14  32  50]
 [ 32  77 122]
 [ 50 122 194]]
Is Matrix D Symetric matrix?
True
